/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** Water coverage of a grid. */
export declare class Mask {
  get width(): number
  get height(): number
  /** Fraction of each pixel that is water, row 0 at the top. */
  coverage(): Float32Array
  /**
   * Shoreline polylines in pixels, water on the left: interleaved x,y and
   * end offsets (in points).
   */
  outlines(): [Float32Array, Uint32Array]
  /** Pixels to the shore: positive in water, negative on land. */
  distance(): Float32Array
}

/** Water gathered from vector tiles. */
export declare class Water {
  constructor()
  /** Read one vector tile (raw or gzipped protobuf). */
  addTile(z: number, x: number, y: number, data: Uint8Array, filterOptions?: FilterOptions | undefined | null): void
  /**
   * Coverage on a north-up Web Mercator grid; height follows the box's
   * shape when left out.
   */
  mask(bounds: Array<number>, width: number, height?: number | undefined | null, supersample?: number | undefined | null, lineWidth?: number | undefined | null): Mask
  /** Waterway lines in pixels of the grid (same packing as outlines). */
  lines(bounds: Array<number>, width: number, height?: number | undefined | null): [Float32Array, Uint32Array]
  lineClasses(): Array<string>
  geojson(): string
  get areaCount(): number
  get lineCount(): number
}

/** Download (or read from the cache) the water in a box. Blocks until done. */
export declare function fetch(bounds: Array<number>, options?: FetchOptions | undefined | null): Water

export interface FetchOptions {
  /** Output width in pixels: picks the tile zoom. */
  width?: number
  height?: number
  /** Tile zoom, instead of width. */
  zoom?: number
  areas?: Array<string>
  lines?: Array<string>
  intermittent?: boolean
  tunnels?: boolean
  /** TileJSON URL or {z}/{x}/{y} template; default OpenFreeMap. */
  source?: string
  /** Cache directory; default $WATERMASK_CACHE or the platform's cache folder. */
  cache?: string
  noCache?: boolean
  maxTiles?: number
}

/** Which features count as water (OpenMapTiles classes). */
export interface FilterOptions {
  /** Area classes; default ocean, lake, river, dock. */
  areas?: Array<string>
  /** Waterway line classes; default river, canal, stream. */
  lines?: Array<string>
  intermittent?: boolean
  tunnels?: boolean
}

/** Tiles covering the box as [z, x, y] (x may exceed 2^z - 1 across 180°). */
export declare function tilesFor(bounds: Array<number>, zoom: number): Array<Array<number>>

export declare function version(): string

/** Tile zoom with at least the detail of `width` pixels across the box. */
export declare function zoomFor(bounds: Array<number>, width: number, maxTiles?: number | undefined | null, maxZoom?: number | undefined | null): number
